### PR TITLE
Fix phy groups

### LINKED ISSUE #79: phy curation issue, files saved incorrectly
We've increasinlgy noticed the same issues we've had with expipe, where channel_group is spontaneously lost during or after curation, causing downstream scripts to err. In one rec (\\aspasia.ad.fp.educloud.no\ec109\maria\mec-social-nwb\actions\148-201021-2\) I've tried phy_restore, re-registered and spikesorted the rec, and keeping an eye on channel_group during curation to avoid information getting lost, but when I went back to inspect a unit, most (if not all) unsorted units were missing channel_group, and several units previously set as noise were now unsorted (see example image).  I have no clue what could be happening, and we have not been able to restore channel_groups in the instances where only a few key units are missing them.  

this unit was set as noise but changed to unosrted (with the appropriate information being kept in cluster_info.tsv):
image
image

this unit lost channel_group, among other info, and therefore cannot be saved:
image
image

I realise this is probably a very convoluted issue but I wanted to inform you and hear if you have any inclination as to what's happening?

### PR DESCRIPTION
**Pull request by alejoe91**
Fixes #79

@mariapfj

What this PR does is to look for "groups" which are "nan" (which is what is loaded when the group is missing) and recomputing the group from the template (taking the group from the channel with the largest amplitude).

Does that sound reasonable?

### CODE REVIEW

**Comment by mariapfj** [comment]
sounds reasonable! would this be automatically perfomed when saving to nwb or do we need to ass an extra step after the curation?

**Comment by alejoe91** [comment]
> sounds reasonable! would this be automatically perfomed when saving to nwb or do we need to ass an extra step after the curation?

Automatic when saving the curated data to NWB

**Comment by alejoe91** [comment]
Ok now the changes should be easier to read :)

**Comment by alejoe91** [comment]
I'll merge to the `bug-fixes` branch, so @lepmik can deploy :)

**Comment by mariapfj** [comment]
Any updates on this, was the bug fix deployed? I'm still having issues with channel_group disappearing, and when it does I cannot load the curated results in jupyter and by extension cannot save to nwb:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File /cluster/software/EL9/easybuild/software/jupyter-server/2.7.2-GCCcore-12.3.0/lib/python3.11/site-packages/ipywidgets/widgets/widget_output.py:103, in Output.capture.<locals>.capture_decorator.<locals>.inner(*args, **kwargs)
    101     self.clear_output(*clear_args, **clear_kwargs)
    102 with self:
--> 103     return func(*args, **kwargs)

File /fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/widgets/curation.py:303, in CurationView.__init__.<locals>.on_load_phy(change)
    301     print("Select one spike sorting output at a time")
    302 else:
--> 303     self.sorting_curator.load_from_phy(sorter_list.value[0])
    304     units = self.sorting_curator.construct_curated_units()
    305     if units:

File /fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/curation.py:195, in SortingCurator.load_from_phy(self, sorter)
    193 print(f"Loaded Phy-curated sorting for {sorter}:\n{sorting_phy}")
    194 sorting_phy.set_property("group", sorting_phy.get_property("channel_group"))
--> 195 self.apply_curation(sorter, sorting_phy)
    196 self.curation_description = "Curation manually performed in Phy."

File /fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/curation.py:159, in SortingCurator.apply_curation(self, sorter, curated_sorting)
    156 compute_and_set_unit_groups(curated_sorting, recording)
    158 print("Extracting waveforms on curated sorting")
--> 159 self.curated_we = si.extract_waveforms(
    160     recording,
    161     curated_sorting,
    162     folder=None,
    163     mode="memory",
    164     max_spikes_per_unit=None,
    165     sparse=True,
    166     method="by_property",
    167     by_property="group",
    168     n_jobs=-1,
    169     progress_bar=False,
    170 )
    171 # recompute PC, template and quality metrics
    172 print("Recomputing PC, template and quality metrics")

File ~/.local/lib/python3.11/site-packages/spikeinterface/core/waveform_extractor.py:1655, in extract_waveforms(recording, sorting, folder, mode, precompute_template, ms_before, ms_after, max_spikes_per_unit, overwrite, return_scaled, dtype, sparse, sparsity, sparsity_temp_folder, num_spikes_for_sparsity, unit_batch_size, allow_unfiltered, use_relative_path, seed, load_if_exists, **kwargs)
   1653         assert all(ch in recording.channel_ids for ch in channels), "Invalid channel ids in sparsity"
   1654 elif sparse:
-> 1655     sparsity = precompute_sparsity(
   1656         recording,
   1657         sorting,
   1658         ms_before=ms_before,
   1659         ms_after=ms_after,
   1660         num_spikes_for_sparsity=num_spikes_for_sparsity,
   1661         unit_batch_size=unit_batch_size,
   1662         temp_folder=sparsity_temp_folder,
   1663         allow_unfiltered=allow_unfiltered,
   1664         **estimate_kwargs,
   1665         **job_kwargs,
   1666     )
   1667 else:
   1668     sparsity = None

File ~/.local/lib/python3.11/site-packages/spikeinterface/core/waveform_extractor.py:1797, in precompute_sparsity(recording, sorting, num_spikes_for_sparsity, unit_batch_size, ms_before, ms_after, temp_folder, allow_unfiltered, **kwargs)
   1782         local_sorting = sorting.select_units(local_ids)
   1783         local_we = extract_waveforms(
   1784             recording,
   1785             local_sorting,
   (...)
   1795             **job_kwargs,
   1796         )
-> 1797         local_sparsity = compute_sparsity(local_we, **sparse_kwargs)
   1798         mask[sl, :] = local_sparsity.mask
   1799 else:

File ~/.local/lib/python3.11/site-packages/spikeinterface/core/sparsity.py:440, in compute_sparsity(templates_or_waveform_extractor, method, peak_sign, num_channels, radius_um, threshold, by_property)
    438 elif method == "by_property":
    439     assert by_property is not None, "For the 'by_property' method, 'by_property' needs to be given"
--> 440     sparsity = ChannelSparsity.from_property(templates_or_waveform_extractor, by_property)
    441 else:
    442     raise ValueError(f"compute_sparsity() method={method} does not exists")

File ~/.local/lib/python3.11/site-packages/spikeinterface/core/sparsity.py:366, in ChannelSparsity.from_property(cls, we, by_property)
    363 for unit_ind, unit_id in enumerate(we.unit_ids):
    364     unit_property = we.sorting.get_property(by_property)[unit_ind]
    365     assert (
--> 366         unit_property in rec_by.keys()
    367     ), f"Unit property {unit_property} cannot be found in the recording properties"
    368     chan_inds = we.recording.ids_to_indices(rec_by[unit_property].get_channel_ids())
    369     mask[unit_ind, chan_inds] = True

AssertionError: Unit property nan cannot be found in the recording properties

**Comment by alejoe91** [comment]
Not sure.. @nicolossus ?

**Comment by nicolossus** [comment]
@alejoe91 @mariapfj The bug fix has been deployed for some time, so I guess the bug persists

**Comment by mariapfj** [comment]
is it possible to simply "move it up" in the pipeline? seems like the initial fix is implemented when saving the curated results, but should rather be when loading the curated results?

**Comment by alejoe91** [comment]
@mariapfj actually the fix is already up (at [line 156](https://github.com/CINPLA/expipe-plugin-cinpla/blob/dev/src/expipe_plugin_cinpla/scripts/curation.py#L156)) and the error is triggered at line 159, but I found a bug in the bug! Should be fixed here: #88

**Pull request merged**
